version: "3.8"
services:
  # registry:
    # image: registry:2
    # container_name: registry
    # ports:
      # - 5000:5000
    # volumes:
      # - /mnt/registry:/var/lib/registry
    # restart: always

  # jenkins:
    # image: jenkins
    # build: ./jenkins
    # container_name: jenkins
    # volumes:
      # - jenkins_home:/var/jenkins_home
      # - /var/run/docker.sock:/var/run/docker.sock
      # - /usr/bin/docker:/usr/bin/docker
      # - esp-binfiles:/var/binfiles
    # ports:
      # - "8080:8080"
      # - "50000:50000"
    # restart: always

  # watchtower:
    # image: containrrr/watchtower
    # container_name: watchtower
    # volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
    # command: --interval 300 --cleanup
    # restart: always

  esp-pir-manager:
    image: localhost:5000/esp-pir-manager
    build: ../services/esp-pir-manager
    container_name: esp-pir-manager
    ports:
      - "9052:9052"
    restart: always

  esp-update-server:
    image: localhost:5000/esp-update-server
    build: ../services/esp-update-server
    container_name: esp-update-server
    volumes:
      - esp-binfiles:/app/binfiles
    ports:
      - "9042:9042"
    restart: always
    
  esp-mqtt-broker:
    image: localhost:5000/esp-mqtt-broker
    build: ../services/esp-mqtt-broker
    container_name: esp-mqtt-broker
    # depends_on:
      # - "mongodb"
    ports:
      - "1883:1883"
      - "1884:1884"
    restart: always
    
  # mongodb:
    # image: ivanmarban/armhf-mongodb
    # container_name: mongodb
    # volumes:
      # - /mnt/mongodb:/var/lib/mongodb
    # ports:
      # - "27017:27017"
    # restart: always
    
  adesso-commuter-server:
    image: localhost:5000/adesso-commuter-server
    build: ../services/adesso-commuter-server
    container_name: adesso-commuter-server
    volumes:
      - /mnt/adesso-commuter-server/screenshots:/app/screenshots
    ports:
      - "9062:9062"
    restart: always

  adesso-commuter-web:
    image: adesso-commuter-web
    build: ../services/adesso-commuter-web
    container_name: adesso-commuter-web
    ports:
      - "9082:80"
    restart: always
  
  alexa-connector:
    image: localhost:5000/alexa-connector
    build: ../services/alexa-connector
    container_name: alexa-connector
    volumes:
      - amazon-env:/app/alexa-remote-control/env
    ports:
      - "9072:9072"
    restart: always

volumes:
  # jenkins_home:
    # name: jenkins_home
  esp-binfiles:
    name: esp-binfiles
  amazon-env:
    name: amazon-env
